### ISSUE TITLE
OCCs were not loaded/started successfully with latest PNOR.

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/op-build#1888] opened 2018-02-20 12:21 UTC
```
--== Welcome to Hostboot hostboot-28927a7/hbicore.bin ==--

  4.04231|secure|SecureROM valid - enabling functionality
  4.05125|secure|Booting in non-secure mode.
  5.55027|Booting from SBE side 0 on master proc=00050000
  5.59912|ISTEP  6. 5 - host_init_fsi
  5.81158|ISTEP  6. 6 - host_set_ipl_parms
  5.86199|ISTEP  6. 7 - host_discover_targets
  7.63258|HWAS|PRESENT> DIMM[03]=AAAA000000000000
  7.63259|HWAS|PRESENT> Proc[05]=8800000000000000
  7.63260|HWAS|PRESENT> Core[07]=FFF0FC3FF3FC0000
  7.66154|ISTEP  6. 8 - host_update_master_tpm
 18.40266|SECURE|Security Access Bit> 0x0000000000000000
 18.40266|SECURE|Secure Mode Disable (via Jumper)> 0xC000000000000000
 18.40278|ISTEP  6. 9 - host_gard
 18.43450|HWAS|FUNCTIONAL> DIMM[03]=AAAA000000000000
 18.43451|HWAS|FUNCTIONAL> Proc[05]=8800000000000000
 18.43452|HWAS|FUNCTIONAL> Core[07]=FFF0FC3FF3FC0000
 18.44109|ISTEP  6.10 - host_revert_sbe_mcs_setup
 18.44270|ISTEP  6.11 - host_start_occ_xstop_handler
 19.29191|ISTEP  6.12 - host_voltage_config
 19.40781|ISTEP  7. 1 - mss_attr_cleanup
 19.73846|ISTEP  7. 2 - mss_volt
 19.83192|ISTEP  7. 3 - mss_freq
 22.23235|ISTEP  7. 4 - mss_eff_config
 23.38300|ISTEP  7. 5 - mss_attr_update
 23.39291|ISTEP  8. 1 - host_slave_sbe_config
 23.50267|ISTEP  8. 2 - host_setup_sbe
 23.51366|ISTEP  8. 3 - host_cbs_start
 23.58936|ISTEP  8. 4 - proc_check_slave_sbe_seeprom_complete
 30.81685|ISTEP  8. 5 - host_attnlisten_proc
 30.81784|ISTEP  8. 6 - host_p9_fbc_eff_config
 30.82399|ISTEP  8. 7 - host_p9_eff_config_links
 30.83286|ISTEP  8. 8 - proc_attr_update
 30.83541|ISTEP  8. 9 - proc_chiplet_fabric_scominit
 30.86717|ISTEP  8.10 - proc_xbus_scominit
 32.76151|ISTEP  8.11 - proc_xbus_enable_ridi
 32.76693|ISTEP  8.12 - host_set_voltages
 32.85852|ISTEP  9. 1 - fabric_erepair
 32.90811|ISTEP  9. 2 - fabric_io_dccal
 33.60786|ISTEP  9. 3 - fabric_pre_trainadv
 33.61204|ISTEP  9. 4 - fabric_io_run_training
 33.74155|ISTEP  9. 5 - fabric_post_trainadv
 33.74437|ISTEP  9. 6 - proc_smp_link_layer
 33.75145|ISTEP  9. 7 - proc_fab_iovalid
 33.77622|ISTEP  9. 8 - host_fbc_eff_config_aggregate
 33.78410|ISTEP 10. 1 - proc_build_smp
 33.92268|ISTEP 10. 2 - host_slave_sbe_update
 34.83451|ISTEP 10. 4 - proc_cen_ref_clk_enable
 34.91909|ISTEP 10. 5 - proc_enable_osclite
 34.92042|ISTEP 10. 6 - proc_chiplet_scominit
 34.97314|ISTEP 10. 7 - proc_abus_scominit
 34.98318|ISTEP 10. 8 - proc_obus_scominit
 35.05510|ISTEP 10. 9 - proc_npu_scominit
 35.09440|ISTEP 10.10 - proc_pcie_scominit
 35.14051|ISTEP 10.11 - proc_scomoverride_chiplets
 35.14251|ISTEP 10.12 - proc_chiplet_enable_ridi
 35.14536|ISTEP 10.13 - host_rng_bist
 35.14752|ISTEP 10.14 - host_update_redundant_tpm
 35.15158|ISTEP 11. 1 - host_prd_hwreconfig
 35.19741|ISTEP 11. 2 - cen_tp_chiplet_init1
 35.20130|ISTEP 11. 3 - cen_pll_initf
 35.20536|ISTEP 11. 4 - cen_pll_setup
 35.21153|ISTEP 11. 5 - cen_tp_chiplet_init2
 35.21714|ISTEP 11. 6 - cen_tp_arrayinit
 35.22146|ISTEP 11. 7 - cen_tp_chiplet_init3
 35.22547|ISTEP 11. 8 - cen_chiplet_init
 35.22938|ISTEP 11. 9 - cen_arrayinit
 35.23476|ISTEP 11.10 - cen_initf
 35.23870|ISTEP 11.11 - cen_do_manual_inits
 35.24299|ISTEP 11.12 - cen_startclocks
 35.24750|ISTEP 11.13 - cen_scominits
 35.25281|ISTEP 12. 1 - mss_getecid
 35.26699|ISTEP 12. 2 - dmi_attr_update
 35.27247|ISTEP 12. 3 - proc_dmi_scominit
 35.27838|ISTEP 12. 4 - cen_dmi_scominit
 35.28284|ISTEP 12. 5 - dmi_erepair
 35.28830|ISTEP 12. 6 - dmi_io_dccal
 35.59765|ISTEP 12. 7 - dmi_pre_trainadv
 35.60173|ISTEP 12. 8 - dmi_io_run_training
 35.61773|ISTEP 12. 9 - dmi_post_trainadv
 35.62164|ISTEP 12.10 - proc_cen_framelock
 35.62575|ISTEP 12.11 - host_startprd_dmi
 35.62944|ISTEP 12.12 - host_attnlisten_memb
 35.63298|ISTEP 12.13 - cen_set_inband_addr
 35.64491|ISTEP 13. 1 - host_disable_memvolt
 35.90030|ISTEP 13. 2 - mem_pll_reset
 35.91937|ISTEP 13. 3 - mem_pll_initf
 35.94698|ISTEP 13. 4 - mem_pll_setup
 35.97484|ISTEP 13. 6 - mem_startclocks
 35.99269|ISTEP 13. 7 - host_enable_memvolt
 35.99654|ISTEP 13. 8 - mss_scominit
 36.37273|ISTEP 13. 9 - mss_ddr_phy_reset
 36.48318|ISTEP 13.10 - mss_draminit
 36.72146|ISTEP 13.11 - mss_draminit_training
 37.67159|ISTEP 13.12 - mss_draminit_trainadv
 37.93130|ISTEP 13.13 - mss_draminit_mc
 37.96691|ISTEP 14. 1 - mss_memdiag
 43.36161|ISTEP 14. 2 - mss_thermal_init
 43.37298|ISTEP 14. 3 - proc_pcie_config
 43.39437|ISTEP 14. 4 - mss_power_cleanup
 43.40114|ISTEP 14. 5 - proc_setup_bars
 43.43946|ISTEP 14. 6 - proc_htm_setup
 43.45111|ISTEP 14. 7 - proc_exit_cache_contained
 43.47518|ISTEP 15. 1 - host_build_stop_image
 45.36624|ISTEP 15. 2 - proc_set_pba_homer_bar
 45.37618|ISTEP 15. 3 - host_establish_ex_chiplet
 45.38462|ISTEP 15. 4 - host_start_stop_engine
 45.40893|ISTEP 16. 1 - host_activate_master
 46.49892|ISTEP 16. 2 - host_activate_slave_cores
 46.79183|ISTEP 16. 3 - host_secure_rng
 46.79986|ISTEP 16. 4 - mss_scrub
 46.81832|ISTEP 16. 5 - host_ipl_complete
 46.86836|ISTEP 16. 6 - host_load_io_ppe
 46.86910|ISTEP 18.11 - proc_tod_setup
 46.98659|ISTEP 18.12 - proc_tod_init
 46.95580|ISTEP 20. 1 - host_load_payload
 47.29532|ISTEP 20. 2 - host_load_hdat
 50.75687|ISTEP 21. 1 - host_runtime_setup
 58.67914|================================================
 58.68224|Error reported by occc (0x2A00) PLID 0x90000039
 58.68382|  <none>
 58.68382|  ModuleId   0x1b unknown
 58.68383|  ReasonCode 0x2a09 unknown
 58.68541|  UserData1   : 0x0000000100000000
 58.68542|  UserData2   : 0x000000000c1b0030
 58.68542|------------------------------------------------
 58.68545|  Callout type             : Hardware Callout
 58.68546|  CPU id                   : 44
 58.68547|  Target                   : Physical:/Sys0/Node0
 58.68547|  Deconfig State           : NO_DECONFIG
 58.68548|  GARD Error Type          : GARD_NULL
 58.68548|  Priority                 : SRCI_PRIORITY_MED
 58.68549|------------------------------------------------
 58.68549|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 58.68550|================================================
 58.97834|htmgt|OCCs are not active (rc=0x2626). Attempting OCC Reset
 60.09233|htmgt|OCCs are not active (rc=0x2625). Attempting OCC Reset
 60.16126|htmgt|OCCs are not active (rc=0x2625). Attempting OCC Reset
 60.22040|htmgt|OCCs are not active (rc=0x2625). Attempting OCC Reset
 60.28307|htmgt|OCCs are not active (rc=0x2625). Attempting OCC Reset
 60.34447|htmgt|OCCs are not active. The system will remain in safe mode (RC: 0x2a09  for OCC0)
 60.34452|htmgt|OCCs are not active. The system will remain in safe mode (RC: 0x2a09  for OCC0)
 60.34457|htmgt|OCCs are not active. The system will remain in safe mode (RC: 0x2a09  for OCC0)
 60.34462|htmgt|OCCs are not active. The system will remain in safe mode (RC: 0x2a09  for OCC0)
 60.34467|htmgt|OCCs are not active. The system will remain in safe mode (RC: 0x2a09  for OCC0)
 60.32543|================================================
 60.32544|Error reported by htmgt (0x2600) PLID 0x90000044
 60.32544|  OCCs were not loaded/started successfully
 60.32545|  ModuleId   0x00 HTMGT_MOD_LOAD_START_STATUS
 60.32546|  ReasonCode 0x2625 HTMGT_RC_OCC_START_FAIL
 60.32546|  UserData1  Failing OCC HUID : 0x0000000000050000
 60.32547|  UserData2   : 0x0000000000000000
 60.32547|------------------------------------------------
 60.32548|  Callout type             : Procedure Callout
 60.32549|  Procedure                : EPUB_PRC_HB_CODE
 60.32549|  Priority                 : SRCI_PRIORITY_LOW
 60.32550|------------------------------------------------
 60.32551|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 60.32551|================================================
 60.78184|================================================
 60.78184|Error reported by htmgt (0x2600) PLID 0x90000045
 60.88567|  OCC reset threshold reached. Leaving OCCs in reset state
 60.88568|  ModuleId   0x07 HTMGT_MOD_OCC_RESET
 60.88568|  ReasonCode 0x2616 HTMGT_RC_OCC_CRIT_FAILURE
 60.88569|  UserData1  return code triggering safe mode : 0x0000000000002a09
 60.88441|  UserData2  OCC instance : 0x0000000000000000
 60.88441|------------------------------------------------
 60.88442|  Callout type             : Procedure Callout
 60.88442|  Procedure                : EPUB_PRC_LVL_SUPP
 60.88443|  Priority                 : SRCI_PRIORITY_MED
 60.88443|------------------------------------------------
 60.88444|  Callout type             : Procedure Callout
 60.88445|  Procedure                : EPUB_PRC_HB_CODE
 60.88445|  Priority                 : SRCI_PRIORITY_MED
 60.88446|------------------------------------------------
 60.88446|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 60.88447|================================================
 60.94532|================================================
 60.94532|Error reported by htmgt (0x2600) PLID 0x90000042
 60.94533|  OCCs were not loaded/started successfully
 60.94533|  ModuleId   0x00 HTMGT_MOD_LOAD_START_STATUS
 60.94534|  ReasonCode 0x2625 HTMGT_RC_OCC_START_FAIL
 60.94534|  UserData1  Failing OCC HUID : 0x0000000000050000
 60.94535|  UserData2   : 0x0000000000000000
 60.94535|------------------------------------------------
 60.94536|  Callout type             : Procedure Callout
 60.94536|  Procedure                : EPUB_PRC_HB_CODE
 60.94537|  Priority                 : SRCI_PRIORITY_LOW
 60.94537|------------------------------------------------
 60.94538|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 60.94538|================================================
 61.03152|================================================
 61.03153|Error reported by hwpf (0x0900) PLID 0x90000043
 61.03153|  HW Procedure generated error. See User Data.
 61.03154|  ModuleId   0x01 MOD_FAPI2_RC_TO_ERRL
 61.03154|  ReasonCode 0x090f RC_HWP_GENERATED_ERROR
 61.03155|  UserData1  RC value from HWP : 0x00000000000e6cc2
 61.03156|  UserData2  <unused> : 0x0000000000000000
 61.03156|------------------------------------------------
 61.05079|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 61.05081|  HWP Error description      : Hardware Image size is not in expected range
 61.05081|------------------------------------------------
 61.02582|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 61.02583|  FFDC                       : HW_IMG_SIZE
 61.02584|     00000000
 61.15047|------------------------------------------------
 61.15048|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 61.15048|  FFDC                       : MAX_HW_IMG_SIZE
 61.15049|     00100000
 61.15053|------------------------------------------------
 61.15054|  Callout type             : Procedure Callout
 61.15054|  Procedure                : EPUB_PRC_HB_CODE
 61.15055|  Priority                 : SRCI_PRIORITY_HIGH
 61.15055|------------------------------------------------
 61.15056|  Callout type             : Procedure Callout
 61.15057|  Procedure                : EPUB_PRC_LVL_SUPP
 61.15057|  Priority                 : SRCI_PRIORITY_MED
 61.15058|------------------------------------------------
 61.15058|  Callout type             : Procedure Callout
 61.15059|  Procedure                : EPUB_PRC_HB_CODE
 61.15059|  Priority                 : SRCI_PRIORITY_MED
 61.15060|------------------------------------------------
 61.15061|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 61.15061|================================================
 61.46365|================================================
 61.46366|Error reported by htmgt (0x2600) PLID 0x90000040
 61.46366|  OCCs were not loaded/started successfully
 61.46367|  ModuleId   0x00 HTMGT_MOD_LOAD_START_STATUS
 61.46367|  ReasonCode 0x2625 HTMGT_RC_OCC_START_FAIL
 61.46368|  UserData1  Failing OCC HUID : 0x0000000000050000
 61.46368|  UserData2   : 0x0000000000000000
 61.46369|------------------------------------------------
 61.46369|  Callout type             : Procedure Callout
 61.46370|  Procedure                : EPUB_PRC_HB_CODE
 61.46370|  Priority                 : SRCI_PRIORITY_LOW
 61.46371|------------------------------------------------
 61.46371|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 61.46372|================================================
 61.55269|================================================
 61.55269|Error reported by hwpf (0x0900) PLID 0x90000041
 61.55270|  HW Procedure generated error. See User Data.
 61.55271|  ModuleId   0x01 MOD_FAPI2_RC_TO_ERRL
 61.55271|  ReasonCode 0x090f RC_HWP_GENERATED_ERROR
 61.55272|  UserData1  RC value from HWP : 0x00000000000e6cc2
 61.55272|  UserData2  <unused> : 0x0000000000000000
 61.55273|------------------------------------------------
 61.55273|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 61.55274|  HWP Error description      : Hardware Image size is not in expected range
 61.55275|------------------------------------------------
 61.55276|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 61.55277|  FFDC                       : HW_IMG_SIZE
 61.55277|     00000000
 61.55283|------------------------------------------------
 61.55284|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 61.55284|  FFDC                       : MAX_HW_IMG_SIZE
 61.55285|     00100000
 61.55288|------------------------------------------------
 61.55288|  Callout type             : Procedure Callout
 61.55289|  Procedure                : EPUB_PRC_HB_CODE
 61.55290|  Priority                 : SRCI_PRIORITY_HIGH
 61.55290|------------------------------------------------
 61.55291|  Callout type             : Procedure Callout
 61.55291|  Procedure                : EPUB_PRC_LVL_SUPP
 61.55292|  Priority                 : SRCI_PRIORITY_MED
 61.55292|------------------------------------------------
 61.55293|  Callout type             : Procedure Callout
 61.55293|  Procedure                : EPUB_PRC_HB_CODE
 61.55294|  Priority                 : SRCI_PRIORITY_MED
 61.55294|------------------------------------------------
 61.55295|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 61.55295|================================================
 62.00611|================================================
 62.00611|Error reported by htmgt (0x2600) PLID 0x9000003E
 62.00612|  OCCs were not loaded/started successfully
 62.00613|  ModuleId   0x00 HTMGT_MOD_LOAD_START_STATUS
 62.00613|  ReasonCode 0x2625 HTMGT_RC_OCC_START_FAIL
 62.00614|  UserData1  Failing OCC HUID : 0x0000000000050000
 62.00614|  UserData2   : 0x0000000000000000
 62.00615|------------------------------------------------
 62.00615|  Callout type             : Procedure Callout
 62.00616|  Procedure                : EPUB_PRC_HB_CODE
 62.00616|  Priority                 : SRCI_PRIORITY_LOW
 62.00617|------------------------------------------------
 62.00617|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 62.00618|================================================
 62.09025|================================================
 62.09025|Error reported by hwpf (0x0900) PLID 0x9000003F
 62.09026|  HW Procedure generated error. See User Data.
 62.09026|  ModuleId   0x01 MOD_FAPI2_RC_TO_ERRL
 62.09027|  ReasonCode 0x090f RC_HWP_GENERATED_ERROR
 62.09029|  UserData1  RC value from HWP : 0x00000000000e6cc2
 62.09030|  UserData2  <unused> : 0x0000000000000000
 62.09030|------------------------------------------------
 62.09031|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 62.09032|  HWP Error description      : Hardware Image size is not in expected range
 62.09033|------------------------------------------------
 62.09033|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 62.09034|  FFDC                       : HW_IMG_SIZE
 62.09035|     00000000
 62.09038|------------------------------------------------
 62.09039|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 62.09039|  FFDC                       : MAX_HW_IMG_SIZE
 62.09040|     00100000
 62.09043|------------------------------------------------
 62.09043|  Callout type             : Procedure Callout
 62.09044|  Procedure                : EPUB_PRC_HB_CODE
 62.09044|  Priority                 : SRCI_PRIORITY_HIGH
 62.09045|------------------------------------------------
 62.09045|  Callout type             : Procedure Callout
 62.09046|  Procedure                : EPUB_PRC_LVL_SUPP
 62.09046|  Priority                 : SRCI_PRIORITY_MED
 62.09047|------------------------------------------------
 62.09047|  Callout type             : Procedure Callout
 62.09048|  Procedure                : EPUB_PRC_HB_CODE
 62.09048|  Priority                 : SRCI_PRIORITY_MED
 62.09049|------------------------------------------------
 62.09050|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 62.09050|================================================
 62.49767|================================================
 62.49768|Error reported by htmgt (0x2600) PLID 0x9000003A
 62.52189|  OCC did not change to requested state
 62.52189|  ModuleId   0x04 HTMGT_MOD_OCCMGR_SET_STATE
 62.52190|  ReasonCode 0x2626 HTMGT_RC_OCC_UNEXPECTED_STATE
 62.52190|  UserData1  requested state : 0x0000000300000004
 62.52191|  UserData2  OCC state : 0x0000000000000000
 62.52191|------------------------------------------------
 62.52192|  Callout type             : Procedure Callout
 62.52193|  Procedure                : EPUB_PRC_HB_CODE
 62.52193|  Priority                 : SRCI_PRIORITY_LOW
 62.52194|------------------------------------------------
 62.52194|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 62.52195|================================================
 62.91099|================================================
 62.91099|Error reported by hwpf (0x0900) PLID 0x9000003D
 62.91100|  HW Procedure generated error. See User Data.
 62.91100|  ModuleId   0x01 MOD_FAPI2_RC_TO_ERRL
 62.91101|  ReasonCode 0x090f RC_HWP_GENERATED_ERROR
 62.91101|  UserData1  RC value from HWP : 0x00000000000e6cc2
 62.91102|  UserData2  <unused> : 0x0000000000000000
 62.91103|------------------------------------------------
 62.91103|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 62.91104|  HWP Error description      : Hardware Image size is not in expected range
 62.91105|------------------------------------------------
 62.91106|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 62.91106|  FFDC                       : HW_IMG_SIZE
 62.91107|     00000000
 62.91110|------------------------------------------------
 62.91111|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 62.91112|  FFDC                       : MAX_HW_IMG_SIZE
 62.91112|     00100000
 62.91115|------------------------------------------------
 62.91116|  Callout type             : Procedure Callout
 62.91116|  Procedure                : EPUB_PRC_HB_CODE
 62.91117|  Priority                 : SRCI_PRIORITY_HIGH
 62.91117|------------------------------------------------
 62.91118|  Callout type             : Procedure Callout
 62.91118|  Procedure                : EPUB_PRC_LVL_SUPP
 62.91119|  Priority                 : SRCI_PRIORITY_MED
 62.91119|------------------------------------------------
 62.91120|  Callout type             : Procedure Callout
 62.91121|  Procedure                : EPUB_PRC_HB_CODE
 62.91121|  Priority                 : SRCI_PRIORITY_MED
 62.91122|------------------------------------------------
 62.91122|  Hostboot Build ID: hostboot-28927a7/hbicore.bin
 62.91123|================================================
 63.24955|ISTEP 21. 2 - host_verify_hdat
 63.23005|ISTEP 21. 3 - host_start_payload
[  103.381908445,5] OPAL skiboot-v5.10-rc3 starting...
```

**Comment by pridhiviraj** [comment] 2018-02-20 12:24
PNOR Level:
```
cat /var/lib/phosphor-software-manager/pnor/ro/VERSION 
open-power-witherspoon-v1.21-rc2-8-gcf83faa-dirty
	buildroot-2017.11-5-g65679be
	skiboot-v5.10-rc3
	hostboot-28927a7
	linux-4.14.20-openpower1-pf1c13fc
	petitboot-v1.6.6-p7cfd0fc
	machine-xml-58554bf-p1f16afe
	occ-f72f857
	hostboot-binaries-6924d6b
	capp-ucode-p9-dd2-v3
	sbe-0aae9a8
```
BMC Level:
```
cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="ibm-v2.1"
VERSION_ID="ibm-v2.1-55-g35bc913-r1-ctm-0-g8b7a6f2"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) ibm-v2.1"
BUILD_ID="ibm-v2.1-55-g35bc913-r1-ctm"
```

**Comment by dcrowell77** [comment] 2018-02-20 22:38
@cjcain

**Comment by cjcain** [comment] 2018-02-20 23:04
This 2A09 is a VRM VDD temperature timeout (1 sec) and the OCC will request a reset when this occurs.  This timeout has since been increased to 5 seconds in a MRW change: SW415109 (end of Jan?)

A PM Complex Reset was issued and I believe succeeded (dont have full eSEL data to know) and then a PM Complex Load/Start, but looks like the hardware procedure failed:
```
 62.09025|Error reported by hwpf (0x0900) PLID 0x9000003F
 62.09026|  HW Procedure generated error. See User Data.
 62.09026|  ModuleId   0x01 MOD_FAPI2_RC_TO_ERRL
 62.09027|  ReasonCode 0x090f RC_HWP_GENERATED_ERROR
 62.09029|  UserData1  RC value from HWP : 0x00000000000e6cc2
 62.09030|  UserData2  <unused> : 0x0000000000000000
 62.09030|------------------------------------------------
 62.09031|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 62.09032|  HWP Error description      : Hardware Image size is not in expected range
 62.09033|------------------------------------------------
 62.09033|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 62.09034|  FFDC                       : HW_IMG_SIZE
 62.09035|     00000000
 62.09038|------------------------------------------------
 62.09039|  HwpReturnCode              : RC_HW_IMAGE_INVALID_SIZE
 62.09039|  FFDC                       : MAX_HW_IMG_SIZE
 62.09040|     00100000
 62.09043|------------------------------------------------
```

**Comment by vanderp** [comment] 2018-02-20 23:14
This is caused by hostboot not pointing to the correct location during hcode_image_build.   

There was a similar problem in HB where Secure Boot changes caused the image rebuild using stale data, thus the failure (0 in image size).   A fix is being worked in SW417728.

**Comment by stewart-ibm** [comment] 2018-05-03 07:30
From reading everything here, I'll close this Issue as something that has been fixed through various means. We can re-open if it's spotted with latest code.

**Closed by stewart-ibm** 2018-05-03 07:30 UTC
